name: Descripting
tagline: "Ali's blog"
markdown: redcarpet
highlighter: pygments
description: "This is blog of Ali Ismayilov, living web developer."
author: Ali Ismayilov
url: "http://alii.pro/blog"
exclude: ['Gemfile', 'Gemfile.lock']
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-sitemap
